Also update 32-bit lists in 64-bit hosts

diff --git a/update-ppa b/update-ppa
--- a/update-ppa
+++ b/update-ppa
@@ -1,6 +1,6 @@
 #!/bin/bash
-# Script to selectively update lists for a PPA in Ubuntu
-# Example: update-ppa ppa:satyajit-happy/themes
+# Script to selectively update lists for a Launchpad PPA in Ubuntu
+# Example: update-ppa ppa:user/repository
 #
 # Copyright (C) 2012  Satyajit sahoo
 #
@@ -36,17 +36,18 @@ if [[ ! $(whoami) = "root" ]]; then
 	exit 1
 fi
 # Detect the required info
-arch="$(uname -m)"
 codename="$(lsb_release -cs)"
 username="$(echo $ppa | cut -f1 -d\/ | cut -f2 -d\:)"
 ppaname="$(echo $ppa | cut -f2 -d\/)"
 release="$(lsb_release -r | cut -f2)"
-# Correct architecture output
+# Detect the architecture
 case `uname -m` in
 	i486|i586|i686)
-		arch="i386";;
+		architectures=( "i386" );;
 	x86_64)
-		arch="amd64";;
+		architectures=( "i386" "amd64" );;
+	*)
+		architectures=( "$(uname -m)" );;		
 esac
 # Ubuntu version for Linux Mint
 case `lsb_release -cs` in
@@ -64,8 +65,8 @@ case `lsb_release -cs` in
 		codename="precise";;
 esac
 # Try to find the codename from the list file
-ppafilename=$(ls /etc/apt/sources.list.d/$username-$ppaname-*.list > /dev/null 2>&1)
-if [[ $? -lt 1 ]]; then
+i=`ls /etc/apt/sources.list.d/$username-$ppaname-*.list > "/dev/null" 2>&1`
+if [[ $? = "0" ]]; then
 codename="$(cat /etc/apt/sources.list.d/$username-$ppaname-*.list | head -1 | cut -f3 -d' ')"
 fi
 version() {
@@ -76,17 +77,17 @@ p=`cat /etc/apt/sources.list /etc/apt/sources.list.d/*.list | grep -i "deb http:
 if [[ ! -n "$p" ]]; then
 	echo -e $RED"The PPA is not present on the system. Do you want to add it first? (y/n)"$ENDCOLOR
 	read response
-	if [[ $(version $release) -gt $(version 11.04) || $codename = "oneiric" || $codename = "precise" || $codename = "quantal" ]]; then
-		case $response in
-			[yY]) add-apt-repository -y "$ppa";;
-			*) exit 1;;
-		esac
-	else
-		case $response in
-			[yY]) add-apt-repository "$ppa";;
-			*) exit 1;;
-		esac
-	fi
+	case $response in
+		[yY])
+			echo -e $BLUE"Adding the PPA..."$ENDCOLOR
+			if [[ $(version $release) -gt $(version 11.04) || $codename = "oneiric" || $codename = "precise" || $codename = "quantal" ]]; then
+				add-apt-repository -y "$ppa"
+			else
+				add-apt-repository "$ppa"
+			fi;;
+		*)
+			exit 1;;
+	esac
 fi
 # Switch to a temporary directory
 tempdir="/tmp/update-ppa"
@@ -95,28 +96,36 @@ if [[ -d "$tempdir" ]]; then
 fi
 mkdir "$tempdir"
 cd "$tempdir"
+# Determine urls and file names
+for arch in "${architectures[@]}"; do
+	urls=( "${urls[@]}" "http://ppa.launchpad.net/${username}/${ppaname}/ubuntu/dists/${codename}/main/binary-${arch}/Packages" )
+	files=( "${files[@]}" "ppa.launchpad.net_${username}_${ppaname}_ubuntu_dists_${codename}_main_binary-${arch}_Packages" )
+done
+urls=( "${urls[@]}" "http://ppa.launchpad.net/${username}/${ppaname}/ubuntu/dists/${codename}/Release" "http://ppa.launchpad.net/${username}/${ppaname}/ubuntu/dists/${codename}/Release.gpg" "http://ppa.launchpad.net/${username}/${ppaname}/ubuntu/dists/${codename}/main/source/Sources" )
+files=( "${files[@]}" "ppa.launchpad.net_${username}_${ppaname}_ubuntu_dists_${codename}_Release" "ppa.launchpad.net_${username}_${ppaname}_ubuntu_dists_${codename}_Release.gpg" "ppa.launchpad.net_${username}_${ppaname}_ubuntu_dists_${codename}_main_source_Sources" )
 # Fetch files to the temporary directory
 echo -e $BLUE"Fetching index files..."$ENDCOLOR
-wget -nv http://ppa.launchpad.net/"$username"/"$ppaname"/ubuntu/dists/"$codename"/Release -O ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"_Release
-wget -nv http://ppa.launchpad.net/"$username"/"$ppaname"/ubuntu/dists/"$codename"/Release.gpg -O ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"_Release.gpg
-wget -nv http://ppa.launchpad.net/"$username"/"$ppaname"/ubuntu/dists/"$codename"/main/binary-"$arch"/Packages -O ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"_main_binary-"$arch"_Packages
-wget -nv http://ppa.launchpad.net/"$username"/"$ppaname"/ubuntu/dists/"$codename"/main/source/Sources -O ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"_main_source_Sources
+for ((i=0; i < "${#urls[@]}"; i++))
+do
+	wget -nv "${urls[i]}" -O "${files[i]}"
+done
 # Move files to the correct location
-if [[ -s ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"_Release && -s ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"_Release.gpg && -s ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"_main_binary-"$arch"_Packages && -s ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"_main_source_Sources ]]; then
-	mv ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"* /var/lib/apt/lists/
-else
-	echo -e $RED"Some index files could not be downloaded or lost :("$ENDCOLOR
-	echo -e "\vPossible reasons may be,\n\v\t[*] The PPA may not be available for your Ubuntu version.\n\t[*] Faulty or no internet connection.\n\vOld index files, if available, will be used instead."
-exit 1
-fi
+for file in "${files[@]}"; do
+	if [[ -s "$file" ]]; then
+		mv -f "$file" "/var/lib/apt/lists/"
+	else
+		echo -e $RED"Some index files could not be downloaded or lost :("$ENDCOLOR
+		echo -e "\vPossible reasons may be,\n\v\t[*] The PPA may not be available for your Ubuntu version.\n\t[*] Faulty or no internet connection.\n\vOld index files, if available, will be used instead."
+		exit 1
+	fi
+	if [[ ! -s "/var/lib/apt/lists/${file}" ]]; then
+		echo -e $RED"An error occured. Please retry :("$ENDCOLOR
+		exit 1
+	fi
+done
 # Delete the temporary directory
 cd ..
 rm -rf "$tempdir"
 # Show success message
-if [[ -s /var/lib/apt/lists/ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"_Release && -s /var/lib/apt/lists/ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"_Release.gpg && -s /var/lib/apt/lists/ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"_main_binary-"$arch"_Packages && -s /var/lib/apt/lists/ppa.launchpad.net_"$username"_"$ppaname"_ubuntu_dists_"$codename"_main_source_Sources ]]; then
-	echo -e $GREEN"The lists for the PPA $ppa have been successfully updated!"$ENDCOLOR
-	exit 0
-else
-	echo -e $RED"An error occured. Please retry :("$ENDCOLOR
-	exit 1
-fi
+echo -e $GREEN"The lists for the PPA $ppa have been successfully updated!"$ENDCOLOR
+exit 0
